name: Deploy to Firebase Hosting on Push
on: 
  push: 
    branches:
      - main   

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4      
      # Upload static HTML files
      - name: Upload Static HTML Files
        uses: actions/upload-artifact@v3
        with:
          name: static-html-files
          path: ./public  # Adjust this path to where your static HTML files are located

      # Download static HTML files (for example, in another job)
      - name: Download Static HTML Files
        uses: actions/download-artifact@v3
        with:
          name: static-html-files
          path: ./public  # Adjust this path as needed

      # Deploy to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TEST_1_CD7E8 }}
          projectId: test-1-cd7e8
