
name: Deploy to Production Website
run-name: Deploy to srinuveer.web.app by @${{ github.actor }} - ${{ github.event.head_commit.message }}

on:
  push:
    branches:
      - main
jobs:
  DeployToProductionWebsite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Zip code artifact
        uses: actions/upload-artifact@v4
        with:
          name: VEER Production Code
          path: .
  release-project:
    runs-on: ubuntu-latest
    needs: DeployToProductionWebsite
    steps:
      - name: unzip code artifact
        uses: actions/download-artifact@v4
        with:
          name: VEER Production Code
          path: .
      - name: Deploying to Production Website
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TEST_1_CD7E8 }}
          channelId: live
          projectId: test-1-cd7e8
