name: Deploy to Firebase Hosting on Push

on: 
  push: 
    branches:
      - main   

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    
      
      # Step 5: Deploy to Firebase Hosting
      - name: Deploy to Production Website
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TEST_1_CD7E8 }}
          projectId: test-1-cd7e8
